### ISSUE TITLE
Gets an about:blank page on when I run the Car class in the Typescript playground

### ISSUE THREAD

**Issue by cloverharvest** [deeleman/angular2-essentials#15]
Chapter 2 , Section on Anatomy of a class – constructors, properties, methods, getters, and setters

1) I ran the ff: code on the TypeScript Playground:

class Car {
  private distanceRun: number = 0;
  color: string;

  constructor(public isHybrid: boolean, color: string = 'red') {
    this.color = color;
  }

  getGasConsumption(): string {
    return this.isHybrid ? 'Very low' : 'Too high!';
  }

  drive(distance: number): void {
    this.distanceRun += distance;
  }

  static honk(): string {
    return 'HOOONK!';
  }

  get distance(): number {
    return this.distanceRun;
  }
}

var myCar = new Car(false);

console.log(myCar.color);     // 'red'
// Public accessor returns distanceRun:
console.log(myCar.distance);  // 0 

myCar.drive(15);
console.log(myCar.distance);  // 15 (0 + 15)
myCar.drive(21);
console.log(myCar.distance);  // 36 (15 + 21)

// What's my carbon footprint according to my car type?
myCar.getGasConsumption();    // 'Too high!' 

Car.honk();   // 'HOOONK!' no object instance required

2) It transpiled to JavaScript

3) But when I pressed Run, I a new page opened but it was blank. (i.e., about:blank)
# 

I know your code is good and working as I picked up the now JavaScript code and ran it on my Google Chrome Dev console and it logged the results as you had written out as comments.

I'm just wondering why it doesn't work with Playground now.

**Comment by deeleman** [comment]
Hi Anna!

I'm afraid the [Playground](https://www.typescriptlang.org/play/index.html) is working as expected. Since we're throwing logging information to the console, it is there where we have to go to find out the output you're after.

Perhaps it did not get clarified enough in the writing, but the TypeScript playground works pretty much as a sandboxed browser window and, as such, you will have to resource on your very own browser deb¡v tools to track whatever is logged through a `console.log` command. 

Should you or any other reader would rather want to have a more visual (and hence convenient) output, you just need to replace the `console.log` statements by mere `document.write` commands. E.g.: Replace the following...

``` javascript
var myCar = new Car(false);

console.log(myCar.color); // 'red'
// Public accessor returns distanceRun:
console.log(myCar.distance); // 0
// etc...
```

by: 

``` javascript
var myCar = new Car(false);

document.write(myCar.color + '<br />'); // 'red'
// Public accessor returns distanceRun:
document.write(myCar.distance + '<br />'); // 0
// etc...
```

Thanks for bringing up this. Please keep sending your questions. This kinda feedback becomes priceless to ensure a better reading experiences for all the community.

**Comment by cloverharvest** [comment]
Thanks, Pablo! I got it. I am learning a lot from your book.
