### ISSUE TITLE
will i able to run the examples in windows machine?

### ISSUE THREAD

**Issue by ksngits** [deeleman/angular2-essentials#21]
Encountered more issues... so giving up. Although I can use mac/linux, still thought of giving try in windows machine.

**Comment by vulkanino** [comment]
I have no issues so far with Windows. What are the problems you are encountering?

**Comment by deeleman** [comment]
The code examples are meant to work seamlessly on a Windows machine @ksngits. It would be helpful if you could provide with more detailed information about what issues are you encountering. Otherwise it's not possible to help. Bear in mind that Angular is widely supported across the board and most of the times the issues arising on a specific platform are due to the way NPM operates in that specific platform and not to angular itself.

**Comment by simonwardle** [comment]
Hi I am having a few problems running the very first example on windows.
When I follow the book I first got problems with typings install es6 but found a post on here that fixed that. The problem I think now is to do with npm downloading @2.0.0-rc.4 instead of rc.1
I have downloaded your project.json I tried to do everything as per the book but when this failed I just removed node_modules and tried doing an npm install with your package.json in place.  This failed because of the preinstall didn't like rm -rf.  I just blanked this out and tried again.
The 'npm install' works but 'npm ls' shows that rc.4 is installed and not rc.1 also it appears that rxjs@5.0.0-beta.6 is missing as this shows UNMET PEER DEPENDENCY.  This is causing problems running the example as @angular/core rc.4 requires it.
If I download your code sample onto my windows machine I can get it all to work but I think this is because your code has the correct versions.  Any help would be great.  I guess I could just try and replace my node_modules with yours but I wanted to try and do it all myself

**Comment by deeleman** [comment]
Hi @simonwardle! Could you please provide a more detailed description of the errors you're getting (preferably in a separate thread/issue)? The code from chapter 1 should run seamlessly on RC.4 though. The current release candidate version does only contain breaking changes that might affect the way forms and animations are handled (chapters 8 and 9, respectively).

All in all, I'd suggest to remove completely your `node_modules` and `typings` folders, execute `npm cache clean` and then proceed with the installation taking the `package.json` file at this repo as the file of reference.
