### ISSUE TITLE
Chapter 4 Section 3

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#31]
In the Component definition the code reads as follows 

```
constructor() {
    const TasksService: TasksService = new TasksService();
    this.tasks = taskService.taskStore;
    this.today = new Date();
  }
```

Firstly, the `TaskService` is defined as `class TaskService` so the first line of the constructor should read 
`const TasksService: TaskService = new TaskService();`

Secondly, if we are going to call the const TasksService then the second line should read
`this.tasks = TasksService.taskStore;`

**Comment by deeleman** [comment]
Damn, now I get it. I'm afraid you are reading a VERY early edition of the book. The code you refer belongs to chapter 5 in the current edition and is now completely different in order to take full advantage of the DI layer.

Would you please check wether the book os named "Angular 2 Essentials"? If so, please refer to Packt with a proof of purchase and request a replacement. 

Packt released that book by mistake and the codebase has dramatically changed ever since. The actual name of the book is "Learning Angular 2" and is up to date with Angular 2 RC.1 (although it should compile seamlessly up to RC.3).

In the meantime, please refer to the code examples in this repository.

**Comment by RichLinnell** [comment]
In reading the book on Safari Books Online. You may need to let them know.

Hopefully I'm not learning the wrong stuff!

Rich.

**Comment by deeleman** [comment]
What is the book name on the frontcover?

**Comment by RichLinnell** [comment]
This is the one I'm reading.
