### ISSUE TITLE
Chapter 7 Section 4 Child Route Changes

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#38]
As we seem to have discovered that the version of the book on Safari Books Online is not the final version of the book, I am not sure if it is worth me continuing to post all the things that I am finding that don't work or not.

Just in case it is, at the end of Section 4, the changes made to introduce the Proxy in front of the timer-widget don't work because we aren't instructed to make corresponding changes to the imports in app.component, or to expose the new directive through the timer.ts facade.

If you want me to stop posting these issues just let me know.  BTW, do you have any idea when Packt might put the correct version onto Safari BOL ? If you think it is going to be within a couple of weeks then I will just leave it at the end of ch. 7 and come back to it when it's correctly published. Whilst I think I am probably more than capable of figuring out what is wrong with the code, it does slow down the learning process, and I have some books on Ionic 2 I want to work through.

**Comment by gtstewart** [comment]
My copy of the book came direct from packt as an ebook and I had similar problems with Chapter 7 and the name of the timer component at the point when the RouteConfig decorator was added because the timer.component.ts was not created until later in the chapter and the timer needed to be added as TimerWidgetComponent and not TimerComponent.I left the name of the route as TimerComponent.

**Comment by fourpastmidnight** [comment]
I found and did the same as @gtstewart.

**Comment by fourpastmidnight** [comment]
I'm also having problems with the initial "try out the route" directions. I got an exception stating that "TasksComponent has no route config".

**Comment by RichLinnell** [comment]
Check the name shouldn't be TaskComponent without the S in the middle. I
had a lot of that.

**Comment by fourpastmidnight** [comment]
@RichLinnell Yes, thanks--unfortunately, not the problem here :wink:. The author did have this component as plural and later it changed to singular. I opted to just keep it plural.

**Comment by fourpastmidnight** [comment]
I figured out why the routing wasn't working. The author started using `TimerComponent` in his example even though he hadn't yet introduced `TimerComponent`, the only timer we had at that time is the `TimerWidgetComponent`. Once I updated the `workOn()` method to navigate to `TimerWidgetComponent`, routing worked.

**Comment by fourpastmidnight** [comment]
Now that I re-read what @gtstewart posted, I see that what I figured out is what he was trying to communicate that he also figured out. So, hopefully between the two of us, others will be able to resolve their problem. :wink:

**Comment by RichLinnell** [comment]
There's other issues on the chapters that follow. But in a way it's good
because it gets you used to the AngularJS error messages and fixing them.
When you get to the testing chapter, make sure you put the html page in the
root of the app and not in the test folder as instructed or you'll be there
for ages trying to work out what's going on. Also it will complain that
resetBaseFilters (or something like that) isn't a method, so I just
commented that line out.

**Comment by deeleman** [comment]
Just for the record, I began writing the book when Angular 2 was still on Alpha stage (alpha v34 actually). Angular 2 went through 20+ alpha versions and 17 beta releases before rushing up into the Release Candidate version (which was a big mistake made by the angular team IMO, mainly bearing in mind the massive amount of breaking changes and dramatic API mutations performed in the framework architecture - that is not what a RC is meant to be according to the software design lifecycle conventions).

On each new alpha/beta/rc release, the book had to be rewritten. At full. Oh my...

In the meantime, there were times that I took the chance to rethink the book project architecture to better suit the new requirements of the Angular API while the chapters were being rewritten. Since Packt forced me to send each chapter as they were written, readers from the Alpha program (an early access program enforced by Packt that allowed subscribers to access raw - unedited, unsync'd - versions of the book as it was being written). Angular 2 kept evolving while these chapters were being redistributed and this turned into a scenario where early subscribers were getting a flawed/unreviewed version of the book in which the educational narrative was broken and thus not consistent. At the light of this, I pondered wether I should rewrite the entire book each time or leave the book review/rewrite to a later stage once all chapters had been defined. I did the latter, and the hardcover edition of the "Learning Angular 2" book is a consistent educational experience where all chapters follow a meaningful and consistent journey.

Unfortunately, someone at Packt uploaded the wrong ebook version to Safari eBooks when the book was finally published, and eventually O'Reilly has been distributing one of those early access versions where some chapters were written according to Angular 2 Beta 15 and some others conformed to the RC.1 version or whatever. As I said earlier, the project depicted in the book evolved as the book was being written and I only standardized all the chapters narrative once all chapters were final, according to RC.1. Previous versions, which were more of a patchwork of unsync'd chapters and thus not meant to be released, featured narrative gaps like the ones reported by all of you guys.

That is why I was so surprised and puzzled in the beginning when I began getting messages like this: I had a hard time figuring out why so many readers reported issues and typos which I could not find myself on my book version. The fact that @RichLinnell pointed out that there was a chapter stating that the router imports were `angular2/router` put me on the right track to unfold the mistery.

Well, what can I say? I am very sorry, and I mean VERY SORRY, that this issue has ruined your reading experience. I've already got in touch with Packt to report this issue (it hasn't been the first time, the first release of the book contained an unedited version of the book as well and lots of irated readers -rightfully- addressed me with complains). 

I would appreciate if you guys could send me over email at deeleman@gmail.com your contact details and ebook purchase details so I can forward them to Packt so you can get the right ebook version. Otherwise you can address the Packt reps yourselves to request the right PDF version and a satisfaction for the inconvenience caused.

On a side note, the new routing API in Angular 2 RC.5 has been fully rewritten, and while the `RouterLink` directive and `RouteConfig` definition still feature the same API, routes need to be defined as standalone classes (not bound to component definitions anymore) and imported into a `@NgModule` class. This introduces a dramatical change in the way routes have to be baked in our projects. Please refer to the official docs for more information on the `@NgModules` API.

Special thanks go to @RichLinnell for shedding light on this issue.

**Comment by deeleman** [comment]
FYI, I've shared all this information with Amit Ramadas, project manager for "Learning Angular 2" at Packt Publishing, so he can take the appropriate action to fix this and address the inconveniences caused to all of you.

**Comment by fourpastmidnight** [comment]
@deelman: Writing a book is hard (so I've heard). It's a little disappointing that the example application seems to be a bit out of synch with the book contents, but I do realize that you were working with pre-release versions of Angular2 which was chaning a great deal between the releases. And so, despite all of that, I do want to say Thanks! for writing the book. Overall, the book is very good. The problems with the examples, while a bit distracting, do give me a chance to exercise the knowledge you've imparted.

It's my hope (as you've already taken steps towards) that Packt will release an updated e-book version of your book with the corrected changes (along with your updates to this repository) to help future readers.

Thanks again for writing the book.

**Comment by deeleman** [comment]
Could you please confirm if any representative from Packt has reached you out already concerning this issue? I received an email a week ago from an editorial rep acknowledging the issue but haven't received any follow up message ever since.

Thanks in advance.

**Comment by fourpastmidnight** [comment]
@deeleman : I have not heard anything from anyone at Packt. _But_, because of my purchases, I got invited via email to speak with someone at Packt about this book. I filled out the form and I am expecting a call on August 30th.

Just to be clear, I think you did a _superb_ job in writing this book. For example, as you commented on another issue I posted here, the Animation API is _totally_ different from what's in Chapter 9. But what you wrote was enough for me to see what's changed, and with the updated Angular 2 docs, I was able to convert the examples to work with the new animation DSL. I think the main problem here is Google not versioning Angular 2 correctly. It's causing problems for authors and publishers, those who decided to start new projects with a purportedly stable pre-release version, and I'm sure the reputation of Angular 2, itself. Publishers make money by printing books for sale, so I'm not sure how much pressure on authors to deliver comes from there, but I've heard it varies by publisher and can be substantial. All that to say I praise you and your authorship skills; I would purchase another book authored by you; I cannot give this particular title high praise, but I hope I've made it abundantly clear that I don't fault you for this. You have been more than responsive and helpful here on this GitHub repo for the book. This is an all around avoidable situation that's caused problems for all of us, but I'm sad to think it's most impactful to you.

**Comment by RichLinnell** [comment]
@deeleman I've heard nothing from Packt here. As others have said, this is a great book marred by publishing errors and a moving target platform. But as I'm sure you've gleaned from this thread, all of the readers have nothing but good things to say about the authorship and quality of the dialogue.

**Comment by deeleman** [comment]
As a follow up to this thread, I'm touch with Reshma Raman, project manager for this book, and I have pointed her out to work this issue out.

First and foremost apologies for the late reply. After nearly nine months of having no personal life whatsoever, mostly due to this book project, I've been focused over the past weeks on catching up with my family and friends and enjoying some personal time, hence the lack of replies.

I'm working now on updating all the examples contained in the book to Angular 2, now it has reached its final version (regardless the huge amount of bugs still arising). The new code release will supersede the current codebase featured in this repository, which will be moved to a legacy branch as a reference. Honestly, it made no sense to carry out this effort earlier given the profound chaos the Angular roadmap has been over the past releases.

Will keep you all posted. Thanks everyone for your support.

**Comment by fourpastmidnight** [comment]
You most certainly deserve to be able to spend time with friends and family!! Thanks for your hard work. I really learned a lot from your book and am very grateful that you wrote it. I'm sorry that it wasn't as great an experience it should've been for you and your readers. Because of your book, though, I was able to adapt the examples to the frequent RC releases of Angular 2. Fortunately, there weren't too many drastic changes after RC5. It appears there's still work being done on the animation API, so it's hit or miss whether you use Angular constructs out just get your hands dirty with CSS. For the throbbing pomodoro, I needed to use CSS. For the fade-in/out of the badges/labels, the Angular animation API worked fine. I haven't touched the forms stuff because that changed almost up until the end.

Once updated for Angular 2 RTW, your example will be superb to get at the fundamentals of how to use Angular 2. I've attempted to read a few other resources on Angular 2, and by far, your book was the most to the point and comprehensive one that I came across.

Thank you!

**Comment by RichLinnell** [comment]
Seconded.

**Comment by gtstewart** [comment]
+1,

While the book and the code were overtaken by the changes being made to RC's. It did give me a considerably understanding of angular 2 programming and has allowed me to develop a small application using the final release and Angular-cli, writing and reading data from a postgresql database using a Java jax-rs interface. I managed to work out how to use Observables, reactive forms and the http, I am yet to tackle the router. 

Keep up the good work and I look forward to an update.

**Comment by RichLinnell** [comment]
Same for me too.

My advice would be :Get ngModules on board too before you go too far and
have to refactor it all.
