### ISSUE TITLE
 "preinstall": "rm -rf ./built",  it does't work in windows 10

### ISSUE THREAD

**Issue by ricardosotogar** [deeleman/angular2-essentials#45]
in the pagake.json this line  "preinstall": "rm -rf ./built"  does't work in windows 10
I think this is for linux. I tried the equivalent for windows 10 with rd \s \q built but it doesn't work either.  What is the right code?

**Comment by deeleman** [comment]
Certainly, the code provided will break on windows. You can just remove the preinstall line either way, since it is not required for the sake of this project.

I'd recommend you to refer to the official docs or the [Angular Quickstart](https://github.com/angular/quickstart) project instead. This book is outdated and no longer relevant, and most of the guidance contained in it is now deprecated

**Comment by Cojak3m** [comment]
Good I haven't opened new issue here as I am having the same problem.
