### ISSUE TITLE
Upgrade at least chapter 1 to Angular 2.0 final

### ISSUE THREAD

**Issue by Rich43** [deeleman/angular2-essentials#49]
Please fix the code in at least Chapter 1 so I can make some sense of AngularJS. Any ETA on upgrading the code base? I have purchased your book.

I like how you install the dependencies individually to avoid some of the bloat of angular-cli. I want to be able to write projects from the ground up.

**Comment by deeleman** [comment]
Hi Ritchie, this link will provide you with the code you need:

https://github.com/deeleman/learning-angular2/tree/v2.1.2/chapter_01

I currently do not have an ETA for releasing an updated codebase. The framework keeps changing quite often and I have actually required Packt to recall the books from the stores, since I believe it is unfair to keep offering an outdated and misleading book to the community. They have disregarded all my pleas.
