### ISSUE TITLE
error regarding npm install systemjs in book

### ISSUE THREAD

**Issue by ykoehler** [deeleman/angular2-essentials#7]
In the book, it says that system js is added as a development dependencies.  Yet the system.js appears to be install with --save and not --save-dev.

```
We will install SystemJS, flagging it as a development dependency by executing the following command:

$ npm install systemjs –save
```

**Comment by deeleman** [comment]
Yep! Actually that is a typo, since `systemjs` will be required either way to spawn the application in both dev and production runtimes so installing it as a non-development dependency (hence `--save`) is the way to go.

I am working on an _Updates_ page that will summarize typos, errata and other amends on the book writing which will be published here on GitHub later next week. I'll keep you posted on this same thread once it goes live.

In the meantime thanks for noticing this error and do not hesitate on highlighting more typos or errors when spotted. I'll be more than happy to help or clarify questions, if any. :)
